<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\JobMarketplace.Applications.Domain\JobMarketplace.Applications.Domain.csproj" />
    <ProjectReference Include="..\..\SharedKernel\JobMarketplace.SharedKernel\JobMarketplace.SharedKernel.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
