name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  AZURE_WEBAPP_NAME: job-market-service
  AZURE_WEBAPP_PACKAGE: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0"

      - name: Restore package
        run: dotnet restore ./JobMarketplace.slnx

      - name: Build package
        run: dotnet build ./JobMarketplace.slnx --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/JobMarketplace.Api/JobMarketplace.Api.csproj --configuration Release --no-build --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE }}'

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "./src/JobMarketplace.Api/publish"
